/**
 * 연주회 인쇄물 테마.
 *
 * 학원마다 색과 분위기가 다르다. 원장이 테마 하나를 고르면 포스터·순서표·초대장·티켓·상장이
 * 모두 같은 옷을 입는다. 색과 서체, 장식, 프레임을 한 벌로 묶어 두는 이유다.
 */

export type OrnamentId =
  | 'keys'
  | 'deco'
  | 'floral'
  | 'leaf'
  | 'stars'
  | 'spotlight'
  | 'holly'
  | 'moon'
  | 'wave'
  /** 금박 이중선 — 격식 있는 초청장 느낌 */
  | 'foil'
  /** 리라(고대 현악기) — 고전 음악회의 상징 */
  | 'lyre'
  /** 잎 갈랜드 — 단정한 화환 */
  | 'garland'
  /** 색종이와 음표 — 축하 분위기 */
  | 'confetti'
  /** 벚꽃 — 봄, 사랑스러운 분위기 */
  | 'cherry'
  /** 눈꽃 — 겨울 발표회 */
  | 'snow'
  /** 단풍 — 가을 음악회 */
  | 'maple'
  /** 리본 매듭 — 선물 같은 초대장 */
  | 'ribbon'
  /** 하트 — 유아·저학년 학부모 초청 */
  | 'heart'
  /** 진주 줄 — 격식 있는 여백형 */
  | 'pearl'
  /** 여름 햇살 */
  | 'sun'
  /** 촛불 — 저녁 공연, 캔들 콘서트 */
  | 'candle'
  /** 담쟁이 덩굴 — 정원·홀 입구 느낌 */
  | 'ivy'
  /** 음표 흩날림 */
  | 'note'
  /** 고전 아치·기둥 — 콘서트홀 정면 */
  | 'arch'
  | 'none'

export type FrameId = 'deco' | 'thin' | 'double' | 'rounded' | 'ribbon' | 'none'

/** 로고를 어떤 모양으로 앉힐지 — 테마 성격에 맞춘다 */
export type LogoShape =
  /** 이미지 그대로 */
  | 'plain'
  /** 원형으로 잘라 넣기 */
  | 'circle'
  /** 원형 + 얇은 금/강조색 테두리 */
  | 'ring'
  /** 밝은 판 위에 올려 어두운 배경에서도 보이게 */
  | 'plate'

/** 사진을 어떤 모양으로 앉힐지 */
export type PhotoShape =
  /** 직각 사각형 */
  | 'rect'
  /** 모서리를 둥글린 사각형 */
  | 'rounded'
  /** 원형 */
  | 'circle'
  /** 위쪽이 둥근 아치 — 무대 커튼 같은 인상 */
  | 'arch'

/**
 * 테마 성격. 원장이 40종을 한 줄로 훑지 않고 "우리 학원 분위기"로 바로 찾게 한다.
 */
export type ThemeFamily = 'classic' | 'lovely' | 'season' | 'modern' | 'kids'

/**
 * 묶음 이름은 **원장님이 자기 연주회를 고르는 말**이라야 한다.
 * "모던 · 편집" 은 디자인 하는 사람의 말이지, 연주회를 준비하시는 분의 말이 아니다.
 * 물음은 하나다 — "우리 연주회 분위기는 어느 쪽인가요?"
 */
export const FAMILY_LABEL: Record<ThemeFamily, string> = {
  classic: '차분하고 격식 있게',
  lovely: '부드럽고 사랑스럽게',
  season: '계절 느낌으로',
  modern: '사진과 큰 글씨로',
  kids: '밝고 아이답게',
}

export const FAMILY_HINT: Record<ThemeFamily, string> = {
  classic: '정통 정기 연주회, 격식 있는 홀. 금선·아치·진주 장식으로 무게를 잡습니다.',
  lovely: '유아·초등 학부모 초청. 부드러운 색과 하트·리본·꽃 장식.',
  season: '봄 벚꽃부터 겨울 눈꽃까지. 시즌 특강 발표회와 계절 음악회에.',
  modern: '사진과 큰 타이포가 주인공. 군더더기 없는 편집 디자인.',
  kids: '색이 밝고 서체가 둥급니다. 놀이형 미니 콘서트에.',
}

export interface DesignTheme {
  id: string
  name: string
  /** 어떤 학원·행사에 어울리는지 한 줄 */
  tagline: string
  mood: string[]
  family: ThemeFamily
  palette: {
    /** 종이 바탕 */
    paper: string
    /** 종이 위 은은한 두 번째 면 */
    paperAlt: string
    ink: string
    muted: string
    accent: string
    accentSoft: string
    line: string
    /** 제목 밴드 등 강한 블록 */
    band: string
    bandInk: string
  }
  fonts: { display: string; body: string }
  ornament: OrnamentId
  frame: FrameId
  /** 배경 질감 */
  texture: 'none' | 'grain' | 'glow' | 'gradient'
  /** 로고 자리 표현 방식과 기본 높이(px, 96dpi 기준) */
  logo: { shape: LogoShape; height: number }
  /** 사진 자리 표현 방식과 톤 보정 */
  photo: { shape: PhotoShape; treatment?: PhotoTreatment }
}

/**
 * 사진 톤 보정 — 학원마다 사진 밝기가 제각각이라 테마 색과 겉돌기 쉽다.
 * natural(그대로) · bright(밝게) · warm(따뜻하게) · soft(부드럽게) · mono(흑백)
 */
export type PhotoTreatment = 'natural' | 'bright' | 'warm' | 'soft' | 'mono'

export const PHOTO_FILTER: Record<PhotoTreatment, string> = {
  natural: 'none',
  bright: 'brightness(1.06) saturate(1.04)',
  warm: 'sepia(0.12) saturate(1.08) brightness(1.02)',
  soft: 'contrast(0.94) brightness(1.04) saturate(0.96)',
  mono: 'grayscale(1) contrast(1.05)',
}

/**
 * 서체 스택.
 *
 * 웹폰트는 인터넷이 있을 때만 내려온다. 없으면 윈도우·맥에 이미 깔린 글꼴로 떨어지는데,
 * 그 폴백까지 손으로 지정해 둬야 인터넷 없는 학원에서도 인쇄물이 제 모양으로 나온다.
 * 윈도우: 바탕(Batang) · 궁서(Gungsuh) · 맑은 고딕(Malgun Gothic)
 * 맥: Apple SD Gothic Neo · AppleMyungjo
 */
const SERIF_CLASSIC =
  "'Nanum Myeongjo', 'Apple SD Gothic Neo', AppleMyungjo, Batang, '바탕', serif"
const SERIF_SOFT = "'Gowun Batang', 'Nanum Myeongjo', AppleMyungjo, Batang, '바탕', serif"
const SERIF_THIN = "'Song Myung', 'Nanum Myeongjo', AppleMyungjo, Batang, '바탕', serif"
const SERIF_NOTO = "'Noto Serif KR', 'Nanum Myeongjo', AppleMyungjo, Batang, '바탕', serif"
const SANS =
  "'Noto Sans KR', Pretendard, 'Apple SD Gothic Neo', 'Malgun Gothic', '맑은 고딕', sans-serif"
// 둥근 글꼴이 없으면 고딕으로 — 각진 명조보다 아이들 인쇄물에 가깝다
const ROUND = "'Jua', 'Noto Sans KR', 'Apple SD Gothic Neo', 'Malgun Gothic', '맑은 고딕', sans-serif"
// 손글씨가 없으면 궁서로 — 붓 느낌이 남는다
const HAND = "'Gaegu', 'Noto Sans KR', Gungsuh, '궁서', 'Malgun Gothic', cursive"

export const DESIGN_THEMES: DesignTheme[] = [
  {
    id: 'daylight-studio',
    name: '데이라이트 스튜디오',
    tagline: '흰 바탕에 사진이 주인공. 실제 사진을 크게 쓰고 싶을 때 가장 잘 맞습니다.',
    mood: ['밝음', '사진', '깨끗'],
    family: 'modern',
    palette: {
      paper: '#ffffff',
      paperAlt: '#f4f5f7',
      ink: '#1c1f24',
      muted: '#6d737d',
      accent: '#2f6f6a',
      accentSoft: '#e3efed',
      line: '#e2e5ea',
      band: '#1c1f24',
      bandInk: '#ffffff',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'wave',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 54 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'sunlit-ivory',
    name: '햇살 아이보리',
    tagline: '창으로 빛이 드는 연습실 같은 밝기. 낮 시간 연주회에.',
    mood: ['밝음', '따뜻', '부드러움'],
    family: 'lovely',
    palette: {
      paper: '#fffdf8',
      paperAlt: '#fdf4e5',
      ink: '#403528',
      muted: '#8b7c66',
      accent: '#bc892c',
      accentSoft: '#f7e9cd',
      line: '#eadcc2',
      band: '#946c23',
      bandInk: '#fffdf8',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'garland',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'rounded', treatment: 'warm' },
  },
  {
    id: 'blossom-white',
    name: '블라썸 화이트',
    tagline: '흰 바탕에 옅은 분홍. 사진이 화사하게 보입니다.',
    mood: ['밝음', '화사', '깨끗'],
    family: 'lovely',
    palette: {
      paper: '#ffffff',
      paperAlt: '#fdf3f4',
      ink: '#3d2f33',
      muted: '#8a757b',
      accent: '#c96b7a',
      accentSoft: '#fbe4e7',
      line: '#f0dde1',
      band: '#bf5062',
      bandInk: '#ffffff',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'floral',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'sky-linen',
    name: '스카이 리넨',
    tagline: '맑은 하늘빛과 리넨 질감. 야외·주말 낮 공연에.',
    mood: ['밝음', '산뜻', '가벼움'],
    family: 'modern',
    palette: {
      paper: '#fbfcfe',
      paperAlt: '#eaf1f8',
      ink: '#22303f',
      muted: '#63768a',
      accent: '#3f7fb0',
      accentSoft: '#dcebf6',
      line: '#d3e0ec',
      band: '#22303f',
      bandInk: '#fbfcfe',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'wave',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'rect', treatment: 'bright' },
  },
  {
    id: 'classic-navy',
    name: '클래식 네이비',
    tagline: '정통 정기 연주회. 격식 있는 공연장, 학부모 초청 행사에.',
    mood: ['정통', '격식', '차분'],
    family: 'classic',
    palette: {
      paper: '#fbfaf6',
      paperAlt: '#f2efe6',
      ink: '#141d33',
      muted: '#5d6478',
      accent: '#b3892f',
      accentSoft: '#e8dcc0',
      line: '#c9c2ae',
      band: '#141d33',
      bandInk: '#f8f5ec',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'deco',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch' },
  },
  {
    id: 'ivory-gold',
    name: '아이보리 골드',
    tagline: '얇은 금선과 여백. 소규모 살롱 연주회에 어울립니다.',
    mood: ['우아', '여백', '고급'],
    family: 'classic',
    palette: {
      paper: '#fdfcf8',
      paperAlt: '#f6f1e4',
      ink: '#3c3527',
      muted: '#8a8069',
      accent: '#ae8d41',
      accentSoft: '#efe5cd',
      line: '#ddd2b6',
      band: '#8c7134',
      bandInk: '#fffdf7',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'keys',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'ring', height: 58 },
    photo: { shape: 'arch' },
  },
  {
    id: 'blush-romance',
    name: '블러시 로맨스',
    tagline: '따뜻하고 부드러운 인상. 유아·초등 학부모 초청에 반응이 좋습니다.',
    mood: ['따뜻', '부드러움', '로맨틱'],
    family: 'lovely',
    palette: {
      paper: '#fffaf8',
      paperAlt: '#fdeee9',
      ink: '#4a2230',
      muted: '#96707b',
      accent: '#c25b70',
      accentSoft: '#f7d9dd',
      line: '#eec9cd',
      band: '#bc4b62',
      bandInk: '#fff6f4',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'floral',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 64 },
    photo: { shape: 'rounded' },
  },
  {
    id: 'forest-calm',
    name: '포레스트 캄',
    tagline: '차분한 초록. 작은 음악회, 정원·카페 공연에.',
    mood: ['차분', '자연', '단정'],
    family: 'modern',
    palette: {
      paper: '#fbfcf8',
      paperAlt: '#eef2e7',
      ink: '#1e3025',
      muted: '#5f7566',
      accent: '#3f6b4a',
      accentSoft: '#d8e5d5',
      line: '#c3d2be',
      band: '#274634',
      bandInk: '#f4f8f0',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'leaf',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded' },
  },
  {
    id: 'modern-mono',
    name: '모던 미니멀',
    tagline: '큰 타이포와 흑백. 세련된 인상을 원하는 학원에.',
    mood: ['모던', '심플', '대담'],
    family: 'modern',
    palette: {
      paper: '#ffffff',
      paperAlt: '#f2f2f2',
      ink: '#111111',
      muted: '#6b6b6b',
      accent: '#111111',
      accentSoft: '#e6e6e6',
      line: '#d4d4d4',
      band: '#111111',
      bandInk: '#ffffff',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'wave',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 52 },
    photo: { shape: 'rect' },
  },
  {
    id: 'pastel-kids',
    name: '파스텔 키즈',
    tagline: '민트와 살구빛. 유아·저학년 발표회에.',
    mood: ['귀여움', '밝음', '아이'],
    family: 'kids',
    palette: {
      paper: '#fdfdfb',
      paperAlt: '#e9f6f2',
      ink: '#28453f',
      muted: '#6f8b85',
      accent: '#e86e40',
      accentSoft: '#ffe3d5',
      line: '#c9e4dc',
      band: '#368274',
      bandInk: '#ffffff',
    },
    fonts: { display: ROUND, body: SANS },
    ornament: 'stars',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 68 },
    photo: { shape: 'circle' },
  },
  {
    id: 'crayon-play',
    name: '크레용 놀이',
    tagline: '손글씨 느낌. 시즌 특강 발표, 놀이형 미니 콘서트에.',
    mood: ['활발', '손글씨', '놀이'],
    family: 'kids',
    palette: {
      paper: '#fffdf5',
      paperAlt: '#fff3d6',
      ink: '#3a2f1d',
      muted: '#8a7a58',
      accent: '#e2721a',
      accentSoft: '#ffe0bd',
      line: '#f0d9a8',
      band: '#f4b63f',
      bandInk: '#3a2f1d',
    },
    fonts: { display: HAND, body: SANS },
    ornament: 'stars',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 68 },
    photo: { shape: 'circle' },
  },
  {
    id: 'midnight-stage',
    name: '미드나잇 스테이지',
    tagline: '어두운 무대와 스포트라이트. 고학년·콩쿠르 입상자 무대에.',
    mood: ['드라마틱', '무대', '집중'],
    family: 'classic',
    palette: {
      paper: '#171922',
      paperAlt: '#1f2330',
      ink: '#f1efe9',
      muted: '#a2a7b8',
      accent: '#d8c07a',
      accentSoft: '#39405a',
      line: '#39405a',
      band: '#d8c07a',
      bandInk: '#171922',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'spotlight',
    frame: 'thin',
    texture: 'glow',
    logo: { shape: 'plate', height: 60 },
    photo: { shape: 'rect' },
  },
  {
    id: 'noir-gold',
    name: '느와르 골드',
    tagline: '검정 바탕에 금박. 정기 연주회를 가장 격식 있게 보이게 합니다.',
    mood: ['고급', '격식', '드라마틱'],
    family: 'classic',
    palette: {
      paper: '#12100f',
      paperAlt: '#1c1917',
      ink: '#f5eee1',
      muted: '#a99e8c',
      accent: '#d4af5f',
      accentSoft: '#3a3226',
      line: '#3f382c',
      band: '#d4af5f',
      bandInk: '#12100f',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'foil',
    frame: 'double',
    texture: 'glow',
    logo: { shape: 'plate', height: 62 },
    photo: { shape: 'rect' },
  },
  {
    id: 'burgundy-velvet',
    name: '버건디 벨벳',
    tagline: '무대 커튼 같은 진홍. 큰 홀에서 여는 정기 연주회에.',
    mood: ['고급', '무대', '깊이'],
    family: 'classic',
    palette: {
      paper: '#3a1220',
      paperAlt: '#4a1a2a',
      ink: '#f8ece8',
      muted: '#cfa8ad',
      accent: '#dcae66',
      accentSoft: '#5c2634',
      line: '#5f2a38',
      band: '#dcae66',
      bandInk: '#3a1220',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'lyre',
    frame: 'double',
    texture: 'glow',
    logo: { shape: 'plate', height: 62 },
    photo: { shape: 'rounded' },
  },
  {
    id: 'sepia-archive',
    name: '세피아 아카이브',
    tagline: '오래된 악보 같은 종이결. 정통성을 강조하고 싶을 때.',
    mood: ['고전', '따뜻', '아카이브'],
    family: 'classic',
    palette: {
      paper: '#f6efdf',
      paperAlt: '#ede3cd',
      ink: '#3b3226',
      muted: '#7d7059',
      accent: '#8a6a3b',
      accentSoft: '#e2d5b8',
      line: '#d5c5a3',
      band: '#3b3226',
      bandInk: '#f6efdf',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'lyre',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'rect' },
  },
  {
    id: 'pearl-mint',
    name: '펄 민트',
    tagline: '맑고 산뜻한 청록. 봄·여름 발표회에 잘 맞습니다.',
    mood: ['산뜻', '맑음', '단정'],
    family: 'season',
    palette: {
      paper: '#f8fbfa',
      paperAlt: '#e8f4f1',
      ink: '#1f3a37',
      muted: '#5f7f7a',
      accent: '#4f9d90',
      accentSoft: '#d5ece6',
      line: '#c6e0da',
      band: '#1f3a37',
      bandInk: '#f8fbfa',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'garland',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded' },
  },
  {
    id: 'moonlit-blue',
    name: '문릿 블루',
    tagline: '달빛 같은 푸른 회색. 야간 공연·녹턴 프로그램에.',
    mood: ['서정', '차분', '밤'],
    family: 'classic',
    palette: {
      paper: '#f0f4fb',
      paperAlt: '#e0e8f5',
      ink: '#1b2a4a',
      muted: '#5d6d8c',
      accent: '#4a6ea9',
      accentSoft: '#d3e0f2',
      line: '#c3d1e8',
      band: '#1b2a4a',
      bandInk: '#f0f4fb',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'wave',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'arch' },
  },
  {
    id: 'spring-bloom',
    name: '스프링 블룸',
    tagline: '연분홍과 연둣빛. 신입생 발표회·봄 음악회에.',
    mood: ['봄', '화사', '경쾌'],
    family: 'season',
    palette: {
      paper: '#fffaf7',
      paperAlt: '#fdeee9',
      ink: '#4a3a2e',
      muted: '#8b7466',
      accent: '#db706a',
      accentSoft: '#e8f0d8',
      line: '#f0dcd2',
      band: '#5e7e48',
      bandInk: '#ffffff',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'confetti',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 64 },
    photo: { shape: 'circle' },
  },
  {
    id: 'christmas-warm',
    name: '크리스마스',
    tagline: '겨울 시즌 발표회와 홈 콘서트에.',
    mood: ['시즌', '따뜻', '겨울'],
    family: 'season',
    palette: {
      paper: '#fdfaf4',
      paperAlt: '#f3eadb',
      ink: '#22372c',
      muted: '#6c7a6c',
      accent: '#a52f38',
      accentSoft: '#f6dcd6',
      line: '#d9c9b4',
      band: '#22372c',
      bandInk: '#fdfaf4',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'holly',
    frame: 'ribbon',
    texture: 'none',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'rounded' },
  },
  {
    id: 'halloween-night',
    name: '할로윈 나이트',
    tagline: '10월 시즌 특강 발표회에.',
    mood: ['시즌', '유쾌', '가을'],
    family: 'season',
    palette: {
      paper: '#1d1526',
      paperAlt: '#2a1f38',
      ink: '#f7efe2',
      muted: '#b6a2c9',
      accent: '#f08a2e',
      accentSoft: '#42305a',
      line: '#4a3763',
      band: '#f08a2e',
      bandInk: '#1d1526',
    },
    fonts: { display: ROUND, body: SANS },
    ornament: 'moon',
    frame: 'none',
    texture: 'glow',
    logo: { shape: 'plate', height: 62 },
    photo: { shape: 'rounded' },
  },

  // ─────────────────────────────────────────────────────────────
  // 고급 · 클래식 — 정통 정기 연주회와 격식 있는 홀
  // ─────────────────────────────────────────────────────────────
  {
    id: 'royal-emerald',
    name: '로열 에메랄드',
    tagline: '깊은 초록과 담쟁이 장식. 격조를 지키면서도 무겁지 않습니다.',
    mood: ['고급', '차분', '격식'],
    family: 'classic',
    palette: {
      paper: '#f7faf7',
      paperAlt: '#e8f1eb',
      ink: '#10261c',
      muted: '#4f6b5c',
      accent: '#1c6b4a',
      accentSoft: '#d5e8dc',
      line: '#c6dbcf',
      band: '#10261c',
      bandInk: '#f7faf7',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'ivy',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'marble-white',
    name: '마블 화이트',
    tagline: '대리석 같은 흰 바탕에 진주 장식. 여백으로 격을 만듭니다.',
    mood: ['고급', '여백', '단정'],
    family: 'classic',
    palette: {
      paper: '#fcfcfd',
      paperAlt: '#f1f0ed',
      ink: '#22242a',
      muted: '#757a85',
      accent: '#8f7f5d',
      accentSoft: '#ece7db',
      line: '#e0dfda',
      band: '#22242a',
      bandInk: '#fcfcfd',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'pearl',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'plain', height: 56 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'vienna-hall',
    name: '비엔나 홀',
    tagline: '크림빛 종이에 진홍과 리라. 유럽 연주회장 프로그램의 인상.',
    mood: ['정통', '고전', '격식'],
    family: 'classic',
    palette: {
      paper: '#fbf6ec',
      paperAlt: '#f3e9d5',
      ink: '#2a1a18',
      muted: '#7a6157',
      accent: '#8c2f39',
      accentSoft: '#f0dcd6',
      line: '#ded0b8',
      band: '#8c2f39',
      bandInk: '#fdf8ef',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'lyre',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 64 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'platinum-grey',
    name: '플래티넘 그레이',
    tagline: '차가운 회색과 고전 아치. 콩쿠르 입상 발표회처럼 절제된 자리에.',
    mood: ['절제', '격식', '모던'],
    family: 'classic',
    palette: {
      paper: '#f8f9fa',
      paperAlt: '#eceef1',
      ink: '#1f2329',
      muted: '#6b7280',
      accent: '#4d5865',
      accentSoft: '#e2e6ea',
      line: '#d7dbe0',
      band: '#1f2329',
      bandInk: '#f8f9fa',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'arch',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 56 },
    photo: { shape: 'rect', treatment: 'mono' },
  },
  {
    id: 'antique-rose',
    name: '앤티크 로즈골드',
    tagline: '바랜 장밋빛과 진주. 오래된 살롱 연주회 같은 온기.',
    mood: ['우아', '따뜻', '고전'],
    family: 'classic',
    palette: {
      paper: '#fdf8f5',
      paperAlt: '#f5e8e0',
      ink: '#3a2a26',
      muted: '#8a6f66',
      accent: '#ad6f5c',
      accentSoft: '#f3e0d7',
      line: '#e6d3c8',
      band: '#8f5645',
      bandInk: '#fffaf7',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'pearl',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'soft' },
  },
  {
    id: 'steinway-black',
    name: '스타인웨이 블랙',
    tagline: '피아노 옻칠 같은 검정에 건반 장식. 고학년 독주회에.',
    mood: ['고급', '집중', '무대'],
    family: 'classic',
    palette: {
      paper: '#0f1114',
      paperAlt: '#191c21',
      ink: '#f3f0ea',
      muted: '#a2a7b0',
      accent: '#c9a86a',
      accentSoft: '#2b2820',
      line: '#33383f',
      band: '#c9a86a',
      bandInk: '#0f1114',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'keys',
    frame: 'thin',
    texture: 'glow',
    logo: { shape: 'plate', height: 60 },
    photo: { shape: 'rect', treatment: 'mono' },
  },
  {
    id: 'opera-crimson',
    name: '오페라 크림슨',
    tagline: '진홍 벨벳과 촛불. 저녁 시간 캔들 콘서트에.',
    mood: ['드라마틱', '따뜻', '저녁'],
    family: 'classic',
    palette: {
      paper: '#2a0f16',
      paperAlt: '#3a1620',
      ink: '#f7ece4',
      muted: '#c9a5a7',
      accent: '#d9a441',
      accentSoft: '#4a1f28',
      line: '#55242f',
      band: '#d9a441',
      bandInk: '#2a0f16',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'candle',
    frame: 'double',
    texture: 'glow',
    logo: { shape: 'plate', height: 62 },
    photo: { shape: 'arch', treatment: 'warm' },
  },

  // ─────────────────────────────────────────────────────────────
  // 사랑스러운 — 유아·초등 학부모 초청
  // ─────────────────────────────────────────────────────────────
  {
    id: 'cotton-candy',
    name: '코튼 캔디',
    tagline: '솜사탕 같은 분홍. 첫 발표회 초대장에 반응이 가장 좋습니다.',
    mood: ['사랑스러움', '부드러움', '밝음'],
    family: 'lovely',
    palette: {
      paper: '#fffafc',
      paperAlt: '#fdeef4',
      ink: '#3f2c35',
      muted: '#8d707c',
      accent: '#d76d9a',
      accentSoft: '#fce1eb',
      line: '#f4dbe4',
      band: '#b45179',
      bandInk: '#fffafc',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'heart',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'lavender-dream',
    name: '라벤더 드림',
    tagline: '연보라와 잔별. 조용하고 사랑스러운 저녁 발표회에.',
    mood: ['사랑스러움', '서정', '차분'],
    family: 'lovely',
    palette: {
      paper: '#fbfaff',
      paperAlt: '#efecfa',
      ink: '#2e2942',
      muted: '#6f6890',
      accent: '#7a68bd',
      accentSoft: '#e6e1f7',
      line: '#ddd7ee',
      band: '#5f4f9e',
      bandInk: '#fbfaff',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'stars',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'peach-blossom',
    name: '피치 블라썸',
    tagline: '복숭아빛과 꽃잎. 사진을 넣으면 얼굴이 화사하게 삽니다.',
    mood: ['사랑스러움', '화사', '따뜻'],
    family: 'lovely',
    palette: {
      paper: '#fffaf6',
      paperAlt: '#fceee2',
      ink: '#3d2b22',
      muted: '#8b6c58',
      accent: '#d4753f',
      accentSoft: '#fbe3d2',
      line: '#f0dbc9',
      band: '#a85628',
      bandInk: '#fffaf6',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'cherry',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'warm' },
  },
  {
    id: 'ribbon-cream',
    name: '리본 크림',
    tagline: '선물 상자를 여는 기분. 리본 띠가 위아래를 감쌉니다.',
    mood: ['사랑스러움', '선물', '단정'],
    family: 'lovely',
    palette: {
      paper: '#fffdf6',
      paperAlt: '#f8efdc',
      ink: '#3b3225',
      muted: '#857662',
      accent: '#c17d95',
      accentSoft: '#f8e6ea',
      line: '#ecdfc9',
      band: '#a65f75',
      bandInk: '#fffdf6',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'ribbon',
    frame: 'ribbon',
    texture: 'none',
    logo: { shape: 'ring', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'bonbon-mint',
    name: '봉봉 민트',
    tagline: '맑은 민트에 색종이. 가볍고 즐거운 미니 콘서트에.',
    mood: ['경쾌', '맑음', '축하'],
    family: 'lovely',
    palette: {
      paper: '#f7fdfb',
      paperAlt: '#e5f6f0',
      ink: '#23342f',
      muted: '#5f7a72',
      accent: '#2f9c81',
      accentSoft: '#d6f0e8',
      line: '#cbe7de',
      band: '#1f7660',
      bandInk: '#f7fdfb',
    },
    fonts: { display: ROUND, body: SANS },
    ornament: 'confetti',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },

  // ─────────────────────────────────────────────────────────────
  // 아이들 · 활기
  // ─────────────────────────────────────────────────────────────
  {
    id: 'milky-bear',
    name: '밀키 베어',
    tagline: '둥근 글씨와 우유빛. 유아 발표회 안내문이 딱딱해 보이지 않습니다.',
    mood: ['아이', '포근', '둥금'],
    family: 'kids',
    palette: {
      paper: '#fffdf7',
      paperAlt: '#f9f0e2',
      ink: '#453727',
      muted: '#8d7a62',
      accent: '#be8740',
      accentSoft: '#f7e7cd',
      line: '#ecdcc3',
      band: '#9a6b32',
      bandInk: '#fffdf7',
    },
    fonts: { display: ROUND, body: ROUND },
    ornament: 'heart',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 64 },
    photo: { shape: 'circle', treatment: 'warm' },
  },

  // ─────────────────────────────────────────────────────────────
  // 계절 · 시즌
  // ─────────────────────────────────────────────────────────────
  {
    id: 'cherry-spring',
    name: '벚꽃 스프링',
    tagline: '흩날리는 벚꽃. 3~4월 신입생 발표회와 봄 음악회에.',
    mood: ['봄', '화사', '사랑스러움'],
    family: 'season',
    palette: {
      paper: '#fffafb',
      paperAlt: '#fdedf1',
      ink: '#3b2b31',
      muted: '#8a6d76',
      accent: '#d2748d',
      accentSoft: '#fbe2e9',
      line: '#f2dbe2',
      band: '#b1566f',
      bandInk: '#fffafb',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'cherry',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'arch', treatment: 'bright' },
  },
  {
    id: 'summer-marine',
    name: '서머 마린',
    tagline: '여름 바다빛과 햇살. 7~8월 방학 특강 발표회에.',
    mood: ['여름', '시원', '산뜻'],
    family: 'season',
    palette: {
      paper: '#f6fbfe',
      paperAlt: '#e4f1f9',
      ink: '#12303f',
      muted: '#55748a',
      accent: '#1e7fa8',
      accentSoft: '#d5eaf5',
      line: '#cbe0ed',
      band: '#12303f',
      bandInk: '#f6fbfe',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'sun',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 56 },
    photo: { shape: 'rect', treatment: 'bright' },
  },
  {
    id: 'autumn-maple',
    name: '어텀 메이플',
    tagline: '단풍빛 종이결. 10~11월 가을 정기 연주회에.',
    mood: ['가을', '따뜻', '차분'],
    family: 'season',
    palette: {
      paper: '#fdf8f1',
      paperAlt: '#f5e9d5',
      ink: '#3a2a1c',
      muted: '#85705a',
      accent: '#b0561f',
      accentSoft: '#f4dcc4',
      line: '#e5d2b6',
      band: '#8e4a1e',
      bandInk: '#fdf8f1',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'maple',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'winter-snow',
    name: '윈터 스노우',
    tagline: '눈 내리는 밝은 겨울. 12~2월 발표회를 산뜻하게.',
    mood: ['겨울', '맑음', '조용'],
    family: 'season',
    palette: {
      paper: '#f8fbfe',
      paperAlt: '#e9f1f8',
      ink: '#1e2c3a',
      muted: '#647688',
      accent: '#5b83ad',
      accentSoft: '#dfeaf5',
      line: '#d3e0ec',
      band: '#1e2c3a',
      bandInk: '#f8fbfe',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'snow',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'newyear-red',
    name: '새해 홍백',
    tagline: '붉은 금선. 신년 음악회와 설 명절 특강 발표에.',
    mood: ['새해', '경사', '격식'],
    family: 'season',
    palette: {
      paper: '#fffcf7',
      paperAlt: '#f8ede0',
      ink: '#2e1c17',
      muted: '#7d6154',
      accent: '#c8352f',
      accentSoft: '#f7ded9',
      line: '#ead9c8',
      band: '#a52a26',
      bandInk: '#fffcf7',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'foil',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'graduation-day',
    name: '졸업의 날',
    tagline: '남보라 화환. 수료식·졸업 연주회와 시상이 있는 자리에.',
    mood: ['졸업', '격식', '축하'],
    family: 'season',
    palette: {
      paper: '#f9f8fc',
      paperAlt: '#edebf6',
      ink: '#23214a',
      muted: '#63618c',
      accent: '#4b4a8f',
      accentSoft: '#e2e0f2',
      line: '#d6d3ea',
      band: '#23214a',
      bandInk: '#f9f8fc',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'garland',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'natural' },
  },

  // ─────────────────────────────────────────────────────────────
  // 모던 · 편집
  // ─────────────────────────────────────────────────────────────
  {
    id: 'gallery-white',
    name: '갤러리 화이트',
    tagline: '장식을 걷어낸 흰 벽. 사진과 글씨만으로 승부합니다.',
    mood: ['모던', '미니멀', '깨끗'],
    family: 'modern',
    palette: {
      paper: '#ffffff',
      paperAlt: '#f4f4f5',
      ink: '#0f0f10',
      muted: '#6e6e73',
      accent: '#0f0f10',
      accentSoft: '#ebebec',
      line: '#dedee0',
      band: '#0f0f10',
      bandInk: '#ffffff',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'note',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 50 },
    photo: { shape: 'rect', treatment: 'natural' },
  },

  // ─────────────────────────────────────────────────────────────
  // 고급 · 클래식 (추가)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ink-scholar',
    name: '먹빛 서재',
    tagline: '먹과 한지. 국악 협연이나 전통 있는 학원의 정기 연주회에.',
    mood: ['정통', '차분', '깊이'],
    family: 'classic',
    palette: {
      paper: '#faf7f0',
      paperAlt: '#eae7df',
      ink: '#1a1a1a',
      muted: '#81807c',
      accent: '#5c5346',
      accentSoft: '#e1ddd5',
      line: '#dbd8d2',
      band: '#1a1a1a',
      bandInk: '#faf7f0',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'foil',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'plain', height: 56 },
    photo: { shape: 'rect', treatment: 'mono' },
  },
  {
    id: 'oxford-green',
    name: '옥스퍼드 그린',
    tagline: '짙은 학문의 초록. 콩쿠르 입상자 무대에.',
    mood: ['격식', '학구', '단정'],
    family: 'classic',
    palette: {
      paper: '#f7f9f6',
      paperAlt: '#e2e9e4',
      ink: '#12241a',
      muted: '#7b867f',
      accent: '#265c3d',
      accentSoft: '#d6e0d8',
      line: '#d7dbd7',
      band: '#12241a',
      bandInk: '#f7f9f6',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'arch',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'bordeaux-linen',
    name: '보르도 리넨',
    tagline: '와인빛과 리넨 결. 저녁 정기 연주회에.',
    mood: ['고급', '따뜻', '격식'],
    family: 'classic',
    palette: {
      paper: '#fbf7f4',
      paperAlt: '#f0e4e2',
      ink: '#2c1a1c',
      muted: '#8b807f',
      accent: '#8c3540',
      accentSoft: '#e9d8d7',
      line: '#ded8d6',
      band: '#5e2129',
      bandInk: '#fbf7f4',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'pearl',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'slate-silver',
    name: '슬레이트 실버',
    tagline: '차가운 석판빛. 군더더기 없는 격식.',
    mood: ['절제', '모던', '격식'],
    family: 'classic',
    palette: {
      paper: '#f7f8f9',
      paperAlt: '#e6e8ea',
      ink: '#1d2228',
      muted: '#818488',
      accent: '#4a5560',
      accentSoft: '#dbdee1',
      line: '#d8dadc',
      band: '#1d2228',
      bandInk: '#f7f8f9',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'arch',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 54 },
    photo: { shape: 'rect', treatment: 'mono' },
  },
  {
    id: 'champagne-gold',
    name: '샴페인 골드',
    tagline: '옅은 금빛 종이. 축하 자리에 어울립니다.',
    mood: ['우아', '축하', '고급'],
    family: 'classic',
    palette: {
      paper: '#fdfaf2',
      paperAlt: '#f4eede',
      ink: '#33301f',
      muted: '#908d80',
      accent: '#a8862e',
      accentSoft: '#efe7d3',
      line: '#e1ded4',
      band: '#6d5719',
      bandInk: '#fdfaf2',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'foil',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'porcelain-blue',
    name: '포슬린 블루',
    tagline: '백자에 청화. 단정하고 서늘한 격식.',
    mood: ['정통', '단정', '서늘'],
    family: 'classic',
    palette: {
      paper: '#f8fafc',
      paperAlt: '#e4eaf0',
      ink: '#16233a',
      muted: '#7e8693',
      accent: '#2f5580',
      accentSoft: '#d8e0e8',
      line: '#d8dce1',
      band: '#16233a',
      bandInk: '#f8fafc',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'pearl',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'mahogany-hall',
    name: '마호가니 홀',
    tagline: '오래된 나무 홀의 색. 큰 무대에.',
    mood: ['고전', '무대', '깊이'],
    family: 'classic',
    palette: {
      paper: '#fbf6ef',
      paperAlt: '#f0e5da',
      ink: '#2e1e12',
      muted: '#8c8178',
      accent: '#8a4a22',
      accentSoft: '#e9dace',
      line: '#ded8d0',
      band: '#4d2a14',
      bandInk: '#fbf6ef',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'lyre',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'pewter-ivory',
    name: '퓨터 아이보리',
    tagline: '무광 주석빛. 사진 없이도 무게가 잡힙니다.',
    mood: ['절제', '여백', '단정'],
    family: 'classic',
    palette: {
      paper: '#fbfaf7',
      paperAlt: '#edebe7',
      ink: '#26262a',
      muted: '#888888',
      accent: '#6b6659',
      accentSoft: '#e4e2de',
      line: '#dddcda',
      band: '#26262a',
      bandInk: '#fbfaf7',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'pearl',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 54 },
    photo: { shape: 'rect', treatment: 'soft' },
  },
  {
    id: 'velvet-plum',
    name: '벨벳 플럼',
    tagline: '자줏빛 벨벳. 겨울 저녁 연주회에.',
    mood: ['고급', '깊이', '저녁'],
    family: 'classic',
    palette: {
      paper: '#faf6f9',
      paperAlt: '#ece3ec',
      ink: '#2a1c2e',
      muted: '#8a808b',
      accent: '#6d3a72',
      accentSoft: '#e3d8e3',
      line: '#ddd7dd',
      band: '#3f2144',
      bandInk: '#faf6f9',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'candle',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'soft' },
  },
  {
    id: 'parchment-sepia',
    name: '파치먼트 세피아',
    tagline: '오래된 악보의 색. 정통성을 강조할 때.',
    mood: ['고전', '따뜻', '아카이브'],
    family: 'classic',
    palette: {
      paper: '#fbf6e9',
      paperAlt: '#f0e8d6',
      ink: '#33291a',
      muted: '#8f8779',
      accent: '#8a6a2c',
      accentSoft: '#e9e0cb',
      line: '#dfd9cc',
      band: '#54401a',
      bandInk: '#fbf6e9',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'lyre',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'plate', height: 58 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'onyx-pearl',
    name: '오닉스 펄',
    tagline: '검정 위의 진주. 가장 격식 있는 초청장.',
    mood: ['고급', '격식', '밤'],
    family: 'classic',
    palette: {
      paper: '#101114',
      paperAlt: '#212224',
      ink: '#f2f0ea',
      muted: '#939290',
      accent: '#cbb27a',
      accentSoft: '#2e2b24',
      line: '#343536',
      band: '#cbb27a',
      bandInk: '#101114',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'pearl',
    frame: 'thin',
    texture: 'glow',
    logo: { shape: 'plate', height: 60 },
    photo: { shape: 'rect', treatment: 'mono' },
  },
  {
    id: 'concert-black',
    name: '콘서트 블랙',
    tagline: '무대 조명이 켜지기 직전. 독주회에.',
    mood: ['무대', '집중', '드라마틱'],
    family: 'classic',
    palette: {
      paper: '#0d0f12',
      paperAlt: '#1e2023',
      ink: '#f0eee9',
      muted: '#91908f',
      accent: '#b9a06a',
      accentSoft: '#292620',
      line: '#313334',
      band: '#b9a06a',
      bandInk: '#0d0f12',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'spotlight',
    frame: 'none',
    texture: 'glow',
    logo: { shape: 'plate', height: 60 },
    photo: { shape: 'arch', treatment: 'mono' },
  },
  {
    id: 'royal-indigo',
    name: '로열 인디고',
    tagline: '깊은 남보라. 시상이 있는 자리에.',
    mood: ['격식', '축하', '깊이'],
    family: 'classic',
    palette: {
      paper: '#171a2e',
      paperAlt: '#272a3d',
      ink: '#eeeef6',
      muted: '#9495a2',
      accent: '#b4a2e0',
      accentSoft: '#30304a',
      line: '#393c4e',
      band: '#b4a2e0',
      bandInk: '#171a2e',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'foil',
    frame: 'double',
    texture: 'glow',
    logo: { shape: 'plate', height: 62 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'forest-night',
    name: '포레스트 나이트',
    tagline: '밤의 숲. 조용하고 단단한 무대.',
    mood: ['차분', '무대', '깊이'],
    family: 'classic',
    palette: {
      paper: '#111c17',
      paperAlt: '#222c27',
      ink: '#eaf0ea',
      muted: '#8f9791',
      accent: '#8fc4a2',
      accentSoft: '#25372d',
      line: '#343e39',
      band: '#8fc4a2',
      bandInk: '#111c17',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'ivy',
    frame: 'thin',
    texture: 'glow',
    logo: { shape: 'plate', height: 58 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'antique-brass',
    name: '앤티크 브라스',
    tagline: '오래 쓴 황동. 손때 묻은 격식.',
    mood: ['고전', '따뜻', '단정'],
    family: 'classic',
    palette: {
      paper: '#faf7f0',
      paperAlt: '#efe9dd',
      ink: '#2b2519',
      muted: '#8a867c',
      accent: '#8a6f2e',
      accentSoft: '#e8e1d1',
      line: '#dddad2',
      band: '#54431a',
      bandInk: '#faf7f0',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'foil',
    frame: 'deco',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'stone-gray',
    name: '스톤 그레이',
    tagline: '돌결 회색. 어떤 사진과도 부딪히지 않습니다.',
    mood: ['중립', '절제', '사진'],
    family: 'classic',
    palette: {
      paper: '#f8f8f7',
      paperAlt: '#e8e8e8',
      ink: '#232426',
      muted: '#858686',
      accent: '#5a5c60',
      accentSoft: '#dfdfdf',
      line: '#dadada',
      band: '#232426',
      bandInk: '#f8f8f7',
    },
    fonts: { display: SERIF_NOTO, body: SANS },
    ornament: 'arch',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'plain', height: 54 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'cathedral-navy',
    name: '커시드럴 네이비',
    tagline: '높은 천장의 남색. 큰 홀 정기 연주회에.',
    mood: ['정통', '격식', '웅장'],
    family: 'classic',
    palette: {
      paper: '#f7f8fb',
      paperAlt: '#e3e6ed',
      ink: '#131c33',
      muted: '#7c818f',
      accent: '#2c4272',
      accentSoft: '#d7dbe5',
      line: '#d7d9df',
      band: '#131c33',
      bandInk: '#f7f8fb',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'arch',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'rosewood-cream',
    name: '로즈우드 크림',
    tagline: '붉은 나뭇결과 크림. 살롱 연주회에.',
    mood: ['우아', '따뜻', '살롱'],
    family: 'classic',
    palette: {
      paper: '#fcf8f3',
      paperAlt: '#f2e7e1',
      ink: '#33231e',
      muted: '#8f8580',
      accent: '#93513c',
      accentSoft: '#ebddd6',
      line: '#e0dad5',
      band: '#5c2e22',
      bandInk: '#fcf8f3',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'pearl',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'soft' },
  },

  // ─────────────────────────────────────────────────────────────
  // 사랑스러운 (추가)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'marshmallow',
    name: '마시멜로',
    tagline: '폭신한 흰빛. 유아 첫 발표회에.',
    mood: ['사랑스러움', '포근', '밝음'],
    family: 'lovely',
    palette: {
      paper: '#fffdfd',
      paperAlt: '#fbf2f4',
      ink: '#3b3134',
      muted: '#958f90',
      accent: '#c57b91',
      accentSoft: '#f9ebee',
      line: '#e4e0e1',
      band: '#a8556c',
      bandInk: '#fffdfd',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'heart',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'apricot-cream',
    name: '애프리콧 크림',
    tagline: '살구빛 크림. 아침 시간 발표회에.',
    mood: ['사랑스러움', '따뜻', '밝음'],
    family: 'lovely',
    palette: {
      paper: '#fffaf4',
      paperAlt: '#fbefe3',
      ink: '#3d2e22',
      muted: '#968c83',
      accent: '#c97e46',
      accentSoft: '#f9e8d9',
      line: '#e4ddd7',
      band: '#a35f24',
      bandInk: '#fffaf4',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'ribbon',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'warm' },
  },
  {
    id: 'mint-blossom',
    name: '민트 블라썸',
    tagline: '민트와 꽃. 봄 소규모 연주회에.',
    mood: ['사랑스러움', '산뜻', '봄'],
    family: 'lovely',
    palette: {
      paper: '#f8fdfa',
      paperAlt: '#e7f4ee',
      ink: '#22332b',
      muted: '#84908a',
      accent: '#479f7c',
      accentSoft: '#dcefe7',
      line: '#dae1dd',
      band: '#2b7157',
      bandInk: '#f8fdfa',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'cherry',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'baby-sky',
    name: '베이비 스카이',
    tagline: '아기 하늘빛. 남아 학부모에게도 잘 맞습니다.',
    mood: ['사랑스러움', '맑음', '가벼움'],
    family: 'lovely',
    palette: {
      paper: '#f9fcff',
      paperAlt: '#e9f1f9',
      ink: '#233040',
      muted: '#858e98',
      accent: '#5590c4',
      accentSoft: '#dfebf6',
      line: '#dbdfe4',
      band: '#2f5f8e',
      bandInk: '#f9fcff',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'stars',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'cocoa-milk',
    name: '코코아 밀크',
    tagline: '따뜻한 코코아색. 겨울 소규모 발표회에.',
    mood: ['사랑스러움', '포근', '겨울'],
    family: 'lovely',
    palette: {
      paper: '#fdfaf6',
      paperAlt: '#f4ece5',
      ink: '#3a2c22',
      muted: '#948b84',
      accent: '#a5714a',
      accentSoft: '#efe4da',
      line: '#e2ddd8',
      band: '#6d4526',
      bandInk: '#fdfaf6',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'heart',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'warm' },
  },
  {
    id: 'lilac-note',
    name: '라일락 노트',
    tagline: '연보라와 음표. 조용한 사랑스러움.',
    mood: ['사랑스러움', '서정', '차분'],
    family: 'lovely',
    palette: {
      paper: '#fcfaff',
      paperAlt: '#f0ecf9',
      ink: '#2f2a3f',
      muted: '#8d8a97',
      accent: '#8272c0',
      accentSoft: '#e8e4f5',
      line: '#dfdde4',
      band: '#574a92',
      bandInk: '#fcfaff',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'note',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'strawberry-cream',
    name: '스트로베리 크림',
    tagline: '딸기와 생크림. 아이들이 가장 좋아합니다.',
    mood: ['사랑스러움', '화사', '달콤'],
    family: 'lovely',
    palette: {
      paper: '#fffafb',
      paperAlt: '#fbecef',
      ink: '#3d2a2e',
      muted: '#968a8c',
      accent: '#d96e80',
      accentSoft: '#f9e4e7',
      line: '#e4ddde',
      band: '#a8404f',
      bandInk: '#fffafb',
    },
    fonts: { display: ROUND, body: SANS },
    ornament: 'heart',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'vanilla-ribbon',
    name: '바닐라 리본',
    tagline: '바닐라빛에 리본 띠. 선물 같은 초대장.',
    mood: ['사랑스러움', '선물', '단정'],
    family: 'lovely',
    palette: {
      paper: '#fffdf7',
      paperAlt: '#f9f3e6',
      ink: '#3a3326',
      muted: '#959086',
      accent: '#ad8b47',
      accentSoft: '#f5eddc',
      line: '#e3e1da',
      band: '#7d6127',
      bandInk: '#fffdf7',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'ribbon',
    frame: 'ribbon',
    texture: 'none',
    logo: { shape: 'ring', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'rose-quartz',
    name: '로즈 쿼츠',
    tagline: '장밋빛 수정. 봄 학부모 초청에.',
    mood: ['사랑스러움', '우아', '봄'],
    family: 'lovely',
    palette: {
      paper: '#fffafb',
      paperAlt: '#f9edf1',
      ink: '#3a2d33',
      muted: '#958b8f',
      accent: '#c47b93',
      accentSoft: '#f6e6ea',
      line: '#e3dddf',
      band: '#93465f',
      bandInk: '#fffafb',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'pearl',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'honey-butter',
    name: '허니 버터',
    tagline: '꿀과 버터. 오후 햇살 아래 연주회에.',
    mood: ['사랑스러움', '따뜻', '밝음'],
    family: 'lovely',
    palette: {
      paper: '#fffcf2',
      paperAlt: '#f9f2de',
      ink: '#3b3320',
      muted: '#958f81',
      accent: '#b38b29',
      accentSoft: '#f6ecd3',
      line: '#e4e0d5',
      band: '#836219',
      bandInk: '#fffcf2',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'sun',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'warm' },
  },
  {
    id: 'powder-blue',
    name: '파우더 블루',
    tagline: '분첩 같은 파랑. 겨울 소규모 발표회에.',
    mood: ['사랑스러움', '차분', '겨울'],
    family: 'lovely',
    palette: {
      paper: '#fafcfe',
      paperAlt: '#ecf1f6',
      ink: '#26303c',
      muted: '#888e95',
      accent: '#6b8fae',
      accentSoft: '#e3ebf1',
      line: '#dcdfe3',
      band: '#3f5f7e',
      bandInk: '#fafcfe',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'snow',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'candy-pop',
    name: '캔디 팝',
    tagline: '알록달록 사탕. 놀이형 미니 콘서트에.',
    mood: ['사랑스러움', '경쾌', '축하'],
    family: 'lovely',
    palette: {
      paper: '#fffcfd',
      paperAlt: '#f9ecf4',
      ink: '#33293a',
      muted: '#918a94',
      accent: '#c25fa8',
      accentSoft: '#f5e3ef',
      line: '#e2dee2',
      band: '#8e2f74',
      bandInk: '#fffcfd',
    },
    fonts: { display: ROUND, body: SANS },
    ornament: 'confetti',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },

  // ─────────────────────────────────────────────────────────────
  // 계절 · 시즌 (추가)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'plum-blossom',
    name: '매화 스프링',
    tagline: '이른 봄 매화. 2~3월 발표회에.',
    mood: ['봄', '단아', '한국'],
    family: 'season',
    palette: {
      paper: '#fffafc',
      paperAlt: '#f9ecf1',
      ink: '#33262c',
      muted: '#91888c',
      accent: '#c4708c',
      accentSoft: '#f6e4ea',
      line: '#e2dcdf',
      band: '#8e3f5c',
      bandInk: '#fffafc',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'cherry',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'arch', treatment: 'bright' },
  },
  {
    id: 'forsythia',
    name: '개나리 옐로',
    tagline: '노란 개나리. 3~4월 신입생 발표회에.',
    mood: ['봄', '화사', '경쾌'],
    family: 'season',
    palette: {
      paper: '#fffdf3',
      paperAlt: '#f9f4de',
      ink: '#3b3620',
      muted: '#959281',
      accent: '#ab8e1a',
      accentSoft: '#f5eed1',
      line: '#e4e1d5',
      band: '#7d6812',
      bandInk: '#fffdf3',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'garland',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'arch', treatment: 'bright' },
  },
  {
    id: 'spring-meadow',
    name: '봄 들판',
    tagline: '연둣빛 들판. 야외 봄 음악회에.',
    mood: ['봄', '산뜻', '자연'],
    family: 'season',
    palette: {
      paper: '#fafdf6',
      paperAlt: '#ecf3e3',
      ink: '#2a3320',
      muted: '#8a9082',
      accent: '#6b9a3a',
      accentSoft: '#e3edd8',
      line: '#dde1d8',
      band: '#41651f',
      bandInk: '#fafdf6',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'leaf',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'arch', treatment: 'bright' },
  },
  {
    id: 'summer-lime',
    name: '서머 라임',
    tagline: '여름 라임빛. 방학 특강 발표회에.',
    mood: ['여름', '경쾌', '시원'],
    family: 'season',
    palette: {
      paper: '#f9fdf6',
      paperAlt: '#eaf3e2',
      ink: '#26331f',
      muted: '#879082',
      accent: '#5f9a2e',
      accentSoft: '#e0edd6',
      line: '#dbe1d8',
      band: '#3b6418',
      bandInk: '#f9fdf6',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'sun',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 56 },
    photo: { shape: 'rect', treatment: 'bright' },
  },
  {
    id: 'ocean-deep',
    name: '오션 딥',
    tagline: '깊은 바다. 여름 저녁 연주회에.',
    mood: ['여름', '깊이', '시원'],
    family: 'season',
    palette: {
      paper: '#f5fafd',
      paperAlt: '#e0ecf2',
      ink: '#12293a',
      muted: '#7a8994',
      accent: '#1f6b91',
      accentSoft: '#d3e3ec',
      line: '#d5dde2',
      band: '#12293a',
      bandInk: '#f5fafd',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'wave',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 56 },
    photo: { shape: 'rect', treatment: 'bright' },
  },
  {
    id: 'watermelon',
    name: '수박 서머',
    tagline: '수박빛 초록과 빨강. 아이들 여름 발표회에.',
    mood: ['여름', '경쾌', '아이'],
    family: 'season',
    palette: {
      paper: '#fafdf8',
      paperAlt: '#e9f2e7',
      ink: '#2b3327',
      muted: '#8a9087',
      accent: '#4d9450',
      accentSoft: '#deecdd',
      line: '#dde1db',
      band: '#2f6533',
      bandInk: '#fafdf8',
    },
    fonts: { display: ROUND, body: SANS },
    ornament: 'sun',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 60 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'harvest-gold',
    name: '하베스트 골드',
    tagline: '가을 들녘의 금빛. 10월 정기 연주회에.',
    mood: ['가을', '따뜻', '풍성'],
    family: 'season',
    palette: {
      paper: '#fdfaf1',
      paperAlt: '#f4eedc',
      ink: '#38301c',
      muted: '#938d7e',
      accent: '#a58224',
      accentSoft: '#efe7d0',
      line: '#e1ded3',
      band: '#6b5314',
      bandInk: '#fdfaf1',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'maple',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'persimmon',
    name: '감빛 어텀',
    tagline: '잘 익은 감색. 11월 늦가을 무대에.',
    mood: ['가을', '따뜻', '한국'],
    family: 'season',
    palette: {
      paper: '#fffaf5',
      paperAlt: '#f8eae0',
      ink: '#3a2a1e',
      muted: '#958a81',
      accent: '#b55f22',
      accentSoft: '#f3e1d3',
      line: '#e3ddd7',
      band: '#7a3d12',
      bandInk: '#fffaf5',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'maple',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'chestnut-brown',
    name: '체스트넛 브라운',
    tagline: '밤빛 갈색. 차분한 가을 연주회에.',
    mood: ['가을', '차분', '따뜻'],
    family: 'season',
    palette: {
      paper: '#fcf8f3',
      paperAlt: '#f1e8e0',
      ink: '#332721',
      muted: '#8f8782',
      accent: '#8a5b38',
      accentSoft: '#eadfd5',
      line: '#e0dbd6',
      band: '#59371f',
      bandInk: '#fcf8f3',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'leaf',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'ring', height: 58 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'frost-white',
    name: '프로스트 화이트',
    tagline: '서리 내린 아침. 12~1월 발표회에.',
    mood: ['겨울', '맑음', '조용'],
    family: 'season',
    palette: {
      paper: '#fafcfe',
      paperAlt: '#eaf0f4',
      ink: '#1f2a35',
      muted: '#848b91',
      accent: '#5d7f9e',
      accentSoft: '#e1e8ef',
      line: '#dbdfe2',
      band: '#1f2a35',
      bandInk: '#fafcfe',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'snow',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'candle-night',
    name: '캔들 나이트',
    tagline: '촛불 하나. 겨울 저녁 캔들 콘서트에.',
    mood: ['겨울', '따뜻', '저녁'],
    family: 'season',
    palette: {
      paper: '#1c1712',
      paperAlt: '#2c2723',
      ink: '#f4ece0',
      muted: '#999389',
      accent: '#d9a441',
      accentSoft: '#3a2e1a',
      line: '#3f3933',
      band: '#d9a441',
      bandInk: '#1c1712',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'candle',
    frame: 'thin',
    texture: 'glow',
    logo: { shape: 'plate', height: 60 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'holly-red',
    name: '홀리 레드',
    tagline: '호랑가시나무 빨강. 크리스마스 발표회에.',
    mood: ['겨울', '시즌', '축하'],
    family: 'season',
    palette: {
      paper: '#fffaf8',
      paperAlt: '#f8e6e4',
      ink: '#2e2020',
      muted: '#8e8483',
      accent: '#b53030',
      accentSoft: '#f3dad8',
      line: '#e2dbda',
      band: '#7a1c1c',
      bandInk: '#fffaf8',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'holly',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'silver-bell',
    name: '실버 벨',
    tagline: '은빛 종. 크리스마스를 차분하게.',
    mood: ['겨울', '시즌', '단정'],
    family: 'season',
    palette: {
      paper: '#f9fafb',
      paperAlt: '#e8ebed',
      ink: '#232830',
      muted: '#85898d',
      accent: '#54606e',
      accentSoft: '#dfe1e4',
      line: '#dbdddf',
      band: '#232830',
      bandInk: '#f9fafb',
    },
    fonts: { display: SERIF_THIN, body: SANS },
    ornament: 'snow',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'circle', height: 58 },
    photo: { shape: 'rounded', treatment: 'soft' },
  },
  {
    id: 'lunar-new-year',
    name: '설날 색동',
    tagline: '색동과 홍백. 설 명절 특강 발표에.',
    mood: ['새해', '한국', '경사'],
    family: 'season',
    palette: {
      paper: '#fffcf6',
      paperAlt: '#f9e9e2',
      ink: '#2e1d18',
      muted: '#8e847e',
      accent: '#c23a2c',
      accentSoft: '#f5ddd6',
      line: '#e2ddd7',
      band: '#8a2119',
      bandInk: '#fffcf6',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'foil',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'warm' },
  },
  {
    id: 'graduation-navy',
    name: '졸업 네이비',
    tagline: '학사모의 남색. 수료식·졸업 연주회에.',
    mood: ['졸업', '격식', '축하'],
    family: 'season',
    palette: {
      paper: '#f8f9fc',
      paperAlt: '#e5e8f1',
      ink: '#1a2140',
      muted: '#808496',
      accent: '#39508c',
      accentSoft: '#d9deea',
      line: '#d9dbe2',
      band: '#1a2140',
      bandInk: '#f8f9fc',
    },
    fonts: { display: SERIF_CLASSIC, body: SANS },
    ornament: 'garland',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 62 },
    photo: { shape: 'arch', treatment: 'natural' },
  },
  {
    id: 'anniversary-rose',
    name: '기념일 로즈',
    tagline: '개원 기념·주년 행사에.',
    mood: ['축하', '기념', '우아'],
    family: 'season',
    palette: {
      paper: '#fffafb',
      paperAlt: '#f8e9ed',
      ink: '#352429',
      muted: '#92868a',
      accent: '#b8506b',
      accentSoft: '#f4dfe4',
      line: '#e3dcde',
      band: '#832a44',
      bandInk: '#fffafb',
    },
    fonts: { display: SERIF_SOFT, body: SANS },
    ornament: 'ribbon',
    frame: 'double',
    texture: 'grain',
    logo: { shape: 'ring', height: 60 },
    photo: { shape: 'arch', treatment: 'soft' },
  },

  // ─────────────────────────────────────────────────────────────
  // 모던 · 편집 (추가)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'editorial-mono',
    name: '에디토리얼 모노',
    tagline: '잡지 같은 흑백 편집. 사진이 강할 때.',
    mood: ['모던', '편집', '대담'],
    family: 'modern',
    palette: {
      paper: '#ffffff',
      paperAlt: '#e7e7e7',
      ink: '#111111',
      muted: '#7e7e7e',
      accent: '#111111',
      accentSoft: '#d9d9d9',
      line: '#dedede',
      band: '#111111',
      bandInk: '#ffffff',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'note',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 50 },
    photo: { shape: 'rect', treatment: 'mono' },
  },
  {
    id: 'paper-craft',
    name: '페이퍼 크래프트',
    tagline: '크라프트 종이결. 손으로 만든 느낌.',
    mood: ['모던', '따뜻', '자연'],
    family: 'modern',
    palette: {
      paper: '#faf6ee',
      paperAlt: '#efe8dd',
      ink: '#332e26',
      muted: '#8f8a82',
      accent: '#8a6f45',
      accentSoft: '#e8e0d3',
      line: '#dedad2',
      band: '#574429',
      bandInk: '#faf6ee',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'leaf',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'plain', height: 54 },
    photo: { shape: 'rect', treatment: 'warm' },
  },
  {
    id: 'grid-blue',
    name: '그리드 블루',
    tagline: '격자와 파랑. 정보가 많은 인쇄물에.',
    mood: ['모던', '명확', '정보'],
    family: 'modern',
    palette: {
      paper: '#f9fbfd',
      paperAlt: '#e5ebf4',
      ink: '#18202e',
      muted: '#80858d',
      accent: '#2f5f9e',
      accentSoft: '#d9e2ee',
      line: '#dadce0',
      band: '#18202e',
      bandInk: '#f9fbfd',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'arch',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 52 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'neon-charcoal',
    name: '네온 차콜',
    tagline: '어두운 회색에 형광 한 점. 고학년 무대에.',
    mood: ['모던', '대담', '무대'],
    family: 'modern',
    palette: {
      paper: '#16181b',
      paperAlt: '#26282b',
      ink: '#f0f1f3',
      muted: '#949698',
      accent: '#7fd4a8',
      accentSoft: '#273632',
      line: '#393b3e',
      band: '#7fd4a8',
      bandInk: '#16181b',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'wave',
    frame: 'none',
    texture: 'glow',
    logo: { shape: 'plate', height: 54 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'warm-minimal',
    name: '웜 미니멀',
    tagline: '따뜻한 회색의 최소주의.',
    mood: ['모던', '절제', '따뜻'],
    family: 'modern',
    palette: {
      paper: '#faf9f7',
      paperAlt: '#edebe8',
      ink: '#2a2724',
      muted: '#8a8885',
      accent: '#7a6f60',
      accentSoft: '#e6e3df',
      line: '#dddcd9',
      band: '#2a2724',
      bandInk: '#faf9f7',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'none',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 50 },
    photo: { shape: 'rect', treatment: 'soft' },
  },
  {
    id: 'duotone-teal',
    name: '듀오톤 틸',
    tagline: '청록 한 색으로 밀어붙인 편집.',
    mood: ['모던', '대담', '산뜻'],
    family: 'modern',
    palette: {
      paper: '#f6fbfb',
      paperAlt: '#e0eded',
      ink: '#12292b',
      muted: '#7b8a8b',
      accent: '#1f6b70',
      accentSoft: '#d4e4e5',
      line: '#d6dede',
      band: '#12292b',
      bandInk: '#f6fbfb',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'wave',
    frame: 'thin',
    texture: 'none',
    logo: { shape: 'plain', height: 52 },
    photo: { shape: 'rect', treatment: 'bright' },
  },
  {
    id: 'poster-red',
    name: '포스터 레드',
    tagline: '강한 빨강 한 색. 멀리서도 읽힙니다.',
    mood: ['모던', '대담', '게시'],
    family: 'modern',
    palette: {
      paper: '#fffafa',
      paperAlt: '#f9e6e6',
      ink: '#26191a',
      muted: '#8a8081',
      accent: '#c32d2d',
      accentSoft: '#f5d9d9',
      line: '#e1dadb',
      band: '#8c1c1c',
      bandInk: '#fffafa',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'none',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 52 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'gallery-sand',
    name: '갤러리 샌드',
    tagline: '모래빛 전시장. 사진을 조용히 받칩니다.',
    mood: ['모던', '사진', '중립'],
    family: 'modern',
    palette: {
      paper: '#faf8f4',
      paperAlt: '#efece6',
      ink: '#2b2823',
      muted: '#8a8883',
      accent: '#8a7c66',
      accentSoft: '#e8e4dd',
      line: '#dddbd7',
      band: '#2b2823',
      bandInk: '#faf8f4',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'none',
    frame: 'none',
    texture: 'none',
    logo: { shape: 'plain', height: 50 },
    photo: { shape: 'rect', treatment: 'natural' },
  },
  {
    id: 'blueprint',
    name: '블루프린트',
    tagline: '설계도 같은 청사진. 진행 문서에 잘 맞습니다.',
    mood: ['모던', '정보', '명확'],
    family: 'modern',
    palette: {
      paper: '#f5f8fb',
      paperAlt: '#e1e8ef',
      ink: '#152234',
      muted: '#7c8490',
      accent: '#2a5580',
      accentSoft: '#d5dee7',
      line: '#d6dadf',
      band: '#152234',
      bandInk: '#f5f8fb',
    },
    fonts: { display: SANS, body: SANS },
    ornament: 'arch',
    frame: 'thin',
    texture: 'grain',
    logo: { shape: 'plain', height: 52 },
    photo: { shape: 'rect', treatment: 'mono' },
  },

  // ─────────────────────────────────────────────────────────────
  // 아이들 · 활기 (추가)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'crayon-box',
    name: '크레용 박스',
    tagline: '색연필 상자. 유아 발표회 안내문에.',
    mood: ['아이', '활발', '놀이'],
    family: 'kids',
    palette: {
      paper: '#fffdf8',
      paperAlt: '#f9f0e3',
      ink: '#3b3325',
      muted: '#959086',
      accent: '#c4762a',
      accentSoft: '#f6e7d7',
      line: '#e4e1da',
      band: '#82471a',
      bandInk: '#fffdf8',
    },
    fonts: { display: ROUND, body: ROUND },
    ornament: 'confetti',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 64 },
    photo: { shape: 'circle', treatment: 'bright' },
  },
  {
    id: 'bubble-pop',
    name: '버블 팝',
    tagline: '동글동글한 거품. 놀이형 미니 콘서트에.',
    mood: ['아이', '경쾌', '놀이'],
    family: 'kids',
    palette: {
      paper: '#f8fdff',
      paperAlt: '#e4f2f7',
      ink: '#233038',
      muted: '#858e94',
      accent: '#2f8fae',
      accentSoft: '#d8ebf2',
      line: '#dae0e3',
      band: '#175d75',
      bandInk: '#f8fdff',
    },
    fonts: { display: ROUND, body: ROUND },
    ornament: 'confetti',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 64 },
    photo: { shape: 'circle', treatment: 'bright' },
  },
  {
    id: 'picnic-check',
    name: '피크닉 체크',
    tagline: '소풍 가는 날. 야외 미니 발표회에.',
    mood: ['아이', '밝음', '야외'],
    family: 'kids',
    palette: {
      paper: '#fbfdf7',
      paperAlt: '#edf3e3',
      ink: '#2d3325',
      muted: '#8c9086',
      accent: '#6f9a30',
      accentSoft: '#e5edd7',
      line: '#dee1da',
      band: '#456418',
      bandInk: '#fbfdf7',
    },
    fonts: { display: ROUND, body: ROUND },
    ornament: 'sun',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'bright' },
  },
  {
    id: 'storybook',
    name: '스토리북',
    tagline: '그림책 같은 색. 이야기가 있는 발표회에.',
    mood: ['아이', '포근', '이야기'],
    family: 'kids',
    palette: {
      paper: '#fffcf4',
      paperAlt: '#f8f0e1',
      ink: '#38301f',
      muted: '#948e81',
      accent: '#b5823a',
      accentSoft: '#f3e8d6',
      line: '#e3dfd6',
      band: '#75521d',
      bandInk: '#fffcf4',
    },
    fonts: { display: ROUND, body: ROUND },
    ornament: 'heart',
    frame: 'rounded',
    texture: 'none',
    logo: { shape: 'circle', height: 62 },
    photo: { shape: 'rounded', treatment: 'warm' },
  },
  {
    id: 'rainbow-play',
    name: '레인보우 플레이',
    tagline: '무지개빛. 가장 밝고 활발한 무대에.',
    mood: ['아이', '활발', '축하'],
    family: 'kids',
    palette: {
      paper: '#fffbfd',
      paperAlt: '#f8e9f3',
      ink: '#332734',
      muted: '#918990',
      accent: '#b5479a',
      accentSoft: '#f3deed',
      line: '#e2dde1',
      band: '#7d2a68',
      bandInk: '#fffbfd',
    },
    fonts: { display: ROUND, body: ROUND },
    ornament: 'confetti',
    frame: 'rounded',
    texture: 'gradient',
    logo: { shape: 'circle', height: 64 },
    photo: { shape: 'circle', treatment: 'bright' },
  },
]

export const DEFAULT_THEME_ID = 'classic-navy'

/** 종이색의 밝기 — 밝은 테마와 어두운 테마를 갈라 보여 주기 위한 판정 */
export function themeLuminance(theme: DesignTheme): number {
  const hex = theme.palette.paper.replace('#', '')
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
  const lin = (c: number) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
}

export function isDarkTheme(theme: DesignTheme): boolean {
  return themeLuminance(theme) < 0.35
}

export function themesByTone(): { tone: 'light' | 'dark'; label: string; items: DesignTheme[] }[] {
  return [
    { tone: 'light', label: '밝은 테마', items: DESIGN_THEMES.filter((t) => !isDarkTheme(t)) },
    { tone: 'dark', label: '어두운 테마', items: DESIGN_THEMES.filter((t) => isDarkTheme(t)) },
  ]
}

export const FAMILY_ORDER: ThemeFamily[] = ['classic', 'lovely', 'season', 'modern', 'kids']

/**
 * 성격별 묶음 — 40종을 한 줄로 늘어놓으면 고를 수가 없다.
 * 원장이 "우리 학원은 이런 분위기" 한 번으로 후보를 5~14종으로 좁히게 한다.
 */
export function themesByFamily(): {
  family: ThemeFamily
  label: string
  hint: string
  items: DesignTheme[]
}[] {
  return FAMILY_ORDER.map((family) => ({
    family,
    label: FAMILY_LABEL[family],
    hint: FAMILY_HINT[family],
    items: DESIGN_THEMES.filter((t) => t.family === family),
  })).filter((g) => g.items.length > 0)
}

/**
 * 행사 날짜로 계절 테마를 추천한다.
 * 원장이 40종을 다 훑지 않아도 "지금 시기에 맞는 것"이 먼저 보이게 하기 위한 것.
 */
export function seasonalThemeIds(month: number): string[] {
  if (month >= 3 && month <= 5) return ['cherry-spring', 'spring-bloom', 'peach-blossom', 'sunlit-ivory']
  if (month >= 6 && month <= 8) return ['summer-marine', 'pearl-mint', 'sky-linen', 'bonbon-mint']
  if (month >= 9 && month <= 11) return ['autumn-maple', 'sepia-archive', 'halloween-night', 'vienna-hall']
  return ['winter-snow', 'christmas-warm', 'newyear-red', 'graduation-day']
}

/**
 * 테마 찾기 — 100종이면 목록을 훑는 것만으로는 못 고른다.
 * 이름·분위기·설명 어디에 걸려도 나오게 한다. "봄", "금", "아이" 처럼 적어도 찾아진다.
 */
export function searchThemes(query: string, within?: ThemeFamily): DesignTheme[] {
  const key = query.trim().toLowerCase()
  const pool = within ? DESIGN_THEMES.filter((t) => t.family === within) : DESIGN_THEMES
  if (!key) return pool
  return DESIGN_THEMES.filter((theme) =>
    [theme.name, theme.tagline, theme.id, ...theme.mood, FAMILY_LABEL[theme.family]]
      .join(' ')
      .toLowerCase()
      .includes(key),
  )
}

export function getTheme(id: string | null | undefined): DesignTheme {
  return DESIGN_THEMES.find((t) => t.id === id) ?? DESIGN_THEMES[0]
}

/** 테마를 CSS 변수로 — 인쇄물 컴포넌트는 이 변수만 참조한다 */
export function themeVars(theme: DesignTheme): Record<string, string> {
  return {
    '--d-paper': theme.palette.paper,
    '--d-paper-alt': theme.palette.paperAlt,
    '--d-ink': theme.palette.ink,
    '--d-muted': theme.palette.muted,
    '--d-accent': theme.palette.accent,
    '--d-accent-soft': theme.palette.accentSoft,
    '--d-line': theme.palette.line,
    '--d-band': theme.palette.band,
    '--d-band-ink': theme.palette.bandInk,
    '--d-display': theme.fonts.display,
    '--d-body': theme.fonts.body,
  }
}
